### ISSUE TITLE
initial pipeline for profile from Genome In A Bottle HiSeq dataset

### ISSUE THREAD

**Issue by dlaehnemann** [hzi-bifo/art_illumina_profiles#1]
For a separate project, we need a good art_illumina profile -- see:
<https://github.com/hzi-bifo/ePySCOPE/issues/39#issuecomment-354984688>

We will therefore make the initial profile generated in this repo:
1. [x] download <ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/NA12878/NIST_NA12878_HG001_HiSeq_300x/RMNISTHS_30xdownsample.bam> and its index <ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/NA12878/NIST_NA12878_HG001_HiSeq_300x/RMNISTHS_30xdownsample.bam.bai>
2. [x] extract the reads from it into `fastq` format, using `samtools fastq`
3. [x] generate art_illumina profile from it

Once the dataset is generated, it should be preserved in a subfolder of this repository, e.g. something like `NA12878_RMNISTHS_30xdownsample`, also documenting the `commit` of the pipeline that was used to generate the profile.

**Comment by VSack** [comment]
I created a working Snakefile and a mini example using the smaller bam-file. Maybe you want to check the folder structure, if you want any changes there before I run the pipeline on the big dataset?

(There are no modules etc. at the moment because this pipeline is really small and there aren't a lot of requirements. I thought that a working pipeline is more important right now to be able to continue with ePyscope asap...)

**Comment by dlaehnemann** [comment]
Just to avoid redundant work, I am currently looking into doing this in a more snakemake-wrappery-style -- so no need to work on this any further until our meeting later today. We can then decide together on how we want to proceed.

**Comment by VSack** [comment]
We now have the profiles for the large `RMNISTHS_30xdownsample.bam`-file. They are located in `/net/sgi/singlecell/art-profiles/art_illumina_profiles/profiles` on the server. I ran the pipeline on one core, which took `samtools` 11h to complete, while the profiler needed 12h for each dataset. So I guess it could be very beneficial to solve that issue #2 (although it might be a user-profile-problem) to check if the pipeline performs fine and faster with more cores.

**Comment by dlaehnemann** [comment]
Thanks for the input on runtimes. I wrapped up my take on issue #2 over there and closed it for now.

As for the profile, could you include it into the workflow repo as an example output, this way we can reference the source of the profile directly. I would:
* [x] create an `example_profile` folder
* [x] copy the two profile files there
* [x] create a README.md in that folder, giving the source link of the dataset and mentioning that it is the commented out example link in the `config.yaml`
* [x] add a new subsection (`##`) `example output` to the main `README.md`, that links to the subfolder
* [x] add and commit it to the repo and push out on GitHub
* [x] also add a link to the `example_profile` folder to the [`resources` folder `README.md` of the epyscope repo](https://github.com/hzi-bifo/ePySCOPE/blob/master/resources/README.md)
* [x] Remove the whole instance of the pipeline from our servers. With the output profiles stored as examples in the main repo, we don't need any of the downloaded and intermediate data and can just free all that space before we forget about it!

Sorry, this is just to make sure we (and others) will be able to find the actual locations of stuff in the future and retrace what we did...

**Comment by dlaehnemann** [comment]
Also, feel free to close this issue once all the above boxes are checked! Yay!
